[[mgr.prepend_keymap]]
on   = "q"
run  = "quit"
desc = "Quit and cd to current directory"

[[mgr.prepend_keymap]]
on   = "Q"
run  = "quit --no-cwd"
desc = "Quit without cd"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = ["enter", "quit"]
desc = "Enter directory and cd quit"

[[mgr.prepend_keymap]]
on   = "m"
run  = "plugin bookmarks save"
desc = "Save bookmark"

[[mgr.prepend_keymap]]
on   = "'"
run  = "plugin bookmarks jump"
desc = "Jump to bookmark"

[[mgr.prepend_keymap]]
on   = ["b", "d"]
run  = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on   = ["b", "D"]
run  = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on   = "n"
run  = "create"
desc = "Create a file"

[[mgr.prepend_keymap]]
on   = "N"
run  = "create --dir"
desc = "Create a directory"
