format = """
$time\
$memory_usage\
$python
$directory\
$git_branch\
$git_status\
"""

[directory]
format = "[ $path > ](fg:#7daea3)"

[git_branch]
format = "[ $branch](fg:#e78a4e)"

[git_status]
format = "[\\($all_status\\) > ](fg:#e78a4e)"

[time]
format = "[【$time】](fg:#ea6962)"
disabled = false

[memory_usage]
format = "[Ram \\[$ram_pct\\] ](fg:#a9b665)"
disabled = false
threshold = 0

[python]
format = "[$virtualenv](fg:#d8a657)"
